# Site settings
title: Akhon Aranyak
email: ekhon_aranyak@yahoo.com
#description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://travel-agent-dora-62747.netlify.com/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  sailik1991

# Build settings
markdown: kramdown
